### ISSUE TITLE
Add Folder resource

### ISSUE THREAD

**Issue by the-it** [grafana/grafonnet#120]
If you look up the api documentation at [here](https://grafana.github.io/grafonnet/API/index.html), you're not finding the folder resources. 

I would expect it to show up at the overview.

**Comment by Duologic** [comment]
The folder resource is not yet supported by Grafonnet.

API documentation exists, should be trivial to add this:
- https://grafana.com/docs/grafana/latest/developers/http_api/folder/

Related, we might also want to manage folder permissions:
- https://grafana.com/docs/grafana/latest/developers/http_api/folder_permissions/#update-permissions-for-a-folder

**Comment by Duologic** [comment]
Looks like this resources is in the schemas for v10.1.0.

**Comment by the-it** [comment]
:partying_face: will it include nested folders as well?

**Comment by Duologic** [comment]
For nested: looks like there is an attribute 'parentUid' that isn't in the schema yet: https://grafana.com/docs/grafana/latest/developers/http_api/folder/
