### ISSUE TITLE
Non-collapsed row has no panels.

### ISSUE THREAD

**Issue by Antiarchitect** [grafana/grafonnet#145]
Not sure if it's a Grafonnet bug at all, but I faced it using Grafonnet:

```
  db.new(input.config.board_title)
  + db.withPanels([
    row.new('Row Name')
    + row.withCollapsed(false)
    + row.withPanels( ... )
```

If using `+ row.withCollapsed(false)` rows are empty (no panels)
If using `+ row.withCollapsed(true)` panels are in place

There is a workaround in not using `rowWithPanels` but flattening row and successive panels but it's not very comfortable to use especially with nested `for` cycles

**Comment by malcolmholmes** [comment]
The json format for rows is odd: for collapsed rows the panels are embedded into the row. For uncollapsed ones, they are *outside* the row, i.e. following the row. Just setting the `row.withCollapsed()` isn't sufficient.

**Comment by Duologic** [comment]
I have written the logic to sort out collapsed rows but it is currently intertwined with `utils.makeGrid()`. It would be a great feature to make this logic available separately.

**Comment by Duologic** [comment]
Calling `util.panel.resolveCollapsedFlagOnRows(panels)` on the eventual array of panels should resolve this (introduced in #155).

https://grafana.github.io/grafonnet/API/util.html#fn-panelresolvecollapsedflagonrows
