### ISSUE TITLE
Support Zabbix 

### ISSUE THREAD

**Issue by stvolinko** [grafana/grafonnet#149]
Is there any chance to get support of zabbix target and queries with https://grafana.com/grafana/plugins/alexanderzobnin-zabbix-app/ plugin?

**Comment by gorokhovdenis** [comment]
Hi team! This feature would greatly simplify our monitoring workflow,. Looking forward to any progress on this.

**Comment by Duologic** [comment]
This would be a nice library but currently we haven't figured out the flow to create libraries for plugins, we'll keep this open as we're looking for possible solutions.

**Comment by Duologic** [comment]
I've made a PR upstream to create a library there: https://github.com/grafana/grafana-zabbix/pull/1770

**Comment by Duologic** [comment]
A library for the zabbix query can be found here: https://github.com/grafana/grafana-zabbix-libsonnet/
