### ISSUE TITLE
g.panel.timeSeries.fieldConfig.defaults.custom.withInsertNulls missing?

### ISSUE THREAD

**Issue by berlincount** [grafana/grafonnet#188]
Hello,

probably a bug in the Grafana schema, but g.panel.timeSeries.fieldConfig.defaults.custom.withInsertNulls - used to show gaps in the data as gaps in the graph seems to be missing.

Any workaround while this needs implementation?

Cheers,

  count

**Comment by Duologic** [comment]
This'll get fixed in future versions, I'd suggest working around by simply adding a JSON blurb to your panel:

```jsonnet
panel + {
  fieldConfig+: {
    defaults+: {
      custom+: {
        insertNulls: '<value>',
      },
    },
  },
}
```
