### ISSUE TITLE
Custom variable not working properly

### ISSUE THREAD

**Issue by DanickBG** [grafana/grafonnet#195]
I am testing the simples version of the custom variable:

```
local g = import 'g.libsonnet';
local var = g.dashboard.variable;
local customVar =
  var.custom.new(
    'myOptions',['a', 'b', 'c', 'd'],
  );
g.dashboard.new('my dashboard')
+ g.dashboard.withVariables([customVar])
```

However, it results in this error:
`RUNTIME ERROR: field does not exist: get
        vendor/github.com/grafana/grafonnet/gen/grafonnet-v10.4.0/clean/../custom/./dashboard/variable.libsonnet:335:17-24       thunk <multi>
        vendor/github.com/grafana/grafonnet/gen/grafonnet-v10.4.0/clean/../custom/./dashboard/../util/./dashboard.libsonnet:27:14-19     object <anonymous>
        vendor/github.com/grafana/grafonnet/gen/grafonnet-v10.4.0/clean/../custom/./dashboard/variable.libsonnet:(333:15)-(336:16)       object <anonymous>
        test.jsonnet:11:30-39   thunk <array_element>
        vendor/github.com/grafana/grafonnet/gen/grafonnet-v10.4.0/clean/dashboard.libsonnet:(210:48)-(212:60)   object <anonymous>
        vendor/github.com/grafana/grafonnet/gen/grafonnet-v10.4.0/clean/dashboard.libsonnet:(210:24)-(212:65)   object <anonymous>
        During manifestation`
        
       However, I can create query variables and manage all the panels which are available, so this error makes no sense to me. Please, help!
       
       
![image](https://github.com/grafana/grafonnet/assets/74489271/67dc987a-fc8f-45c6-b72d-fcc7941523eb)

**Comment by DanickBG** [comment]
@Duologic I updated and still get the same results, any other advice? 
I would really appreciate if you can help me so we can others who face the same problem in the future.

**Comment by malcolmholmes** [comment]
Not sure what is in the python bindings for Jsonnet. Does it also pull in Jsonnet itself? You will want to run go-jsonnet not default C jsonnet.

**Comment by DanickBG** [comment]
Unfortunately I can't understand what you mean @malcolmholmes :(
I have no go-jsonnet command which I can run, only jsonnet, despite having downloaded everything as stated in Readme. 
If you tell me explicitly how to run go-jsonnet then I can try to do it :)

**Comment by DanickBG** [comment]
![image](https://github.com/grafana/grafonnet/assets/74489271/28e3ac25-3930-4a13-8ac9-65a36aa10bf6)
@malcolmholmes 
Mine says:
`Jsonnet commandline interpreter (Go implementation) v0.20.0
`
