### ISSUE TITLE
AlertList panel does not work anymore on latest version

### ISSUE THREAD

**Issue by RorFis** [grafana/grafonnet#201]
Hi, I tried to upload multiple dashboards today on Grafana (some that I modified and some I did not). I'm using Jenkins to upload my dashboard and it pulls the latest grafonnet version. I have an Alert List dashboard with multiple Alert List panels that I did not modified and used to work with the previous grafonnet version. 

However today it seems that the dashboard does not work anymore. I identified the following json code : 
`      "pluginVersion": "v11.0.0",
      "title": "Business Alerts",
      "type": "AlertList"`

However, a working json is the following : 
`      "pluginVersion": "v11.0.0",
      "title": "Business Alerts",
      "type": "alertlist"`

Is there a way to change the type ?
Thanks

**Comment by Duologic** [comment]
Not fixed, I'm afk now.
