### ISSUE TITLE
standardOptions.mapping.ValueMap.withType('value') not working on v11.0.0

### ISSUE THREAD

**Issue by RorFis** [grafana/grafonnet#202]
Hi, I tried to generate a dashboard with value Mapping but I have the following error : 
`RUNTIME ERROR: function expected 0 positional argument(s), but got 1`

It seems something changed with standardOptions.mapping.ValueMap.withType(). How can I use it ?

**Comment by Duologic** [comment]
You can drop the argument, the `type` value is a constant and is now set directly.

Also see PR description other changs: https://github.com/grafana/grafonnet/pull/199 ;)
