### ISSUE TITLE
libraryPanel and #something.LibraryPanel

### ISSUE THREAD

**Issue by hAh0L13** [grafana/grafonnet#234]
Hello.
I'm using grafonnet 10.3

Most panels have `libraryPanel` object, i.e. [stat](https://grafana.github.io/grafonnet/API/panel/stat/index.html#obj-librarypanel). Object provide two functions:

- withName
- withUid

But libraryPanel have more functions, i.e. [withType](https://grafana.github.io/grafonnet/API/librarypanel/index.html#fn-withtype). How I should use it? When I creating dashboard with Stat panel describing libraryPanel, inside Grafana it expects `type` field, which stay empty. Is it normal behavior or I should define `type` inside libraryPanel object?
![Image](https://github.com/user-attachments/assets/e7c3a60a-3520-4fe9-a54c-3bba2a7767bb)
P.S. This question inspired by problem with importing generated dashboard with librarypanels - [link](https://github.com/grafana/grafana/issues/95558#issuecomment-2517989649)

**Comment by Duologic** [comment]
The upstream schema does not specify more than these two values, I personally have very little experience with library panels so I'm afraid I'm not much of a help. I generally stick to writing jsonnet libraries for panels instead of using the libraryPanel feature.

FWIW, this part of the library may be able to help you: https://grafana.github.io/grafonnet/API/librarypanel/index.html

**Comment by hAh0L13** [comment]
It seems I have solved this issue. I found the following code in the file raw/panel.libsonnet and reused it
```
  '#withLibraryPanel': { 'function': { args: [{ default: null, enums: null, name: 'value', type: ['object'] }], help: 'A library panel is a reusable panel that you can use in any dashboard.\nWhen you make a change to a library panel, that change propagates to all instances of where the panel is used.\nLibrary panels streamline reuse of panels across multiple dashboards.' } },
  withLibraryPanel(value): {
    libraryPanel: value,
  },
```
As a result, I call `withLibraryPanel` and reference librarypanel.libsonnet inside it

This allowed me to use all the necessary fields. As a result, a correct schema is created, and the import is successful. Thank you very much.
