### ISSUE TITLE
Location of source code

### ISSUE THREAD

**Issue by geowatson** [grafana/grafonnet#25]
Where can I contribute in order to implement missing features?

**Comment by malcolmholmes** [comment]
What missing features are you wanting to implement?

This repo is generated from the CUE schema in Grafana itself, so if a field or plugin are missing, they need to be added in the plugin or component itself.

**Comment by geowatson** [comment]
for example, i want to do the following:
```
g.dashboard.new('My dashboard')
+ g.dashboard.withUid("my-dashboard")
+ g.dashboard.withTemplateVariables([
  var.new('datasource', 'datasource')
    + var.withQuery('prometheus')
    + var.withRegex('prometheus-prod'),
  var.new('namespace', 'constant')
    + var.withQuery('default'),
  var.new('cluster', 'query')
    + var.query.withLabelValues('cluster', 'up')
    // this is because there is no withVisibility option right now
    // hide: 0 is visible variable,
    // hide: 1 variable name is not visible
    // hide: 2 variable is invisible
    + { hide: 2 }
```

or 
```
+ g.dashboard.withPanels(
  [
    g.panel.timeSeries.new("Panel demo")
    + { transparent: true } // -> not implemented

```

**Comment by geowatson** [comment]
i am using g, vars:
```
local g = import 'github.com/grafana/grafonnet/gen/grafonnet-v9.4.0/main.libsonnet';
local var = g.dashboard.templating.list;

```

**Comment by malcolmholmes** [comment]
I'd rather we avoid creating veneer fixes for schema limitations. There is a risk we forget to fix the schema then see the same issue reoccur as we use the schema in other contexts.

**Comment by geowatson** [comment]
What should I do if I want those changes ASAP in the library for creating my project?

**Comment by malcolmholmes** [comment]
I would suggest two things:

* create a github.com/grafana/grafana ticket requesting the entry be added to the schema
* create a small wrapper library to add it for yourself.

In the case of that library, if you follow the `g.libsonnet` pattern used in the grafonnet examples, you can both import grafonnet, and patch it, in one place (in `g.lubsonnet`) and your patches will be available to all invocations of Grafonnet. Once Grafana has the fix, you can remove it without your users noticing.
