### ISSUE TITLE
Adding Alert Provisioning

### ISSUE THREAD

**Issue by sulli204** [grafana/grafonnet#69]
Hi I was curious if the Grafonnet team was going to add Alert Provisioning/Alerting/Alert Rules to dashboards and relating the to panels in the near future?

**Comment by malcolmholmes** [comment]
Hi, yeah, we would love to have library support for alerting/etc. We can't make promises about timelines yet though.

**Comment by Duologic** [comment]
For reference, the API docs: https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/
