### ISSUE TITLE
Grafana 8.x support

### ISSUE THREAD

**Issue by DifferentialOrange** [grafana/grafonnet#73]
Grafana 8.x hasn't reached its end of life yet: https://endoflife.date/grafana. Our team policy doesn't allow us to drop 8.x support for dashboards since 8.x is still supported by Grafana team itself. But in that case we'll need to continue to use deprecated library with various workarounds.

Since new library is autogenerated, is it possible to make it compatible with 8.x code?

**Comment by Duologic** [comment]
This library depends on schema's coming from Grafana, the 8.x branches do not have these schema's so we can not support it in Grafonnet.

**Comment by DifferentialOrange** [comment]
Well, that's sad yet expected
