### ISSUE TITLE
Terraform error with matcher

### ISSUE THREAD

**Issue by kelchen123** [grafana/grafonnet#87]
When using Terraform for my dashboard, I encountered the below error. Terraform works well when I comment out the lines containing "matcher", such as g.panel.table.fieldOverride.matcher.withId('id'), but otherwise:

terraform apply
╷
│ Error: RUNTIME ERROR: Field does not exist: matcher
│ 	/tmp/jsonnet/main.libsonnet:6338:15-50	
│ 	Array element 0	
│ 	Field "overrides"	
│ 	Field "fieldConfig"	
│ 	Array element 0	
│ 	Field "panels"	
│ 	Array element 12	
│ 	Field "panels"	
│ 	During manifestation	
│ 
│ 
│   with data.jsonnet_file.dashboard,
│   on dashboard.tf line 14, in data "jsonnet_file" "dashboard":
│   14: data "jsonnet_file" "dashboard" {
│

**Comment by kelchen123** [comment]
Hi, just wondering if there are any updates or explanations for this error. Thanks!

**Comment by malcolmholmes** [comment]
Can you give us some code to look at?

**Comment by sebhoss** [comment]
@kelchen123 I think your code is wrong because there is no `matcher` in [fieldOverride](https://grafana.github.io/grafonnet/API/panel/table/fieldOverride.html) but there is a `matcher` in the resulting JSON. So the correct usage is something like this:

Jsonnet:

```jsonnet
grafonnet.panel.table.standardOptions.withOverrides([
  grafonnet.panel.table.fieldOverride.byName.new("some-name")
  + grafonnet.panel.table.fieldOverride.byName.withPropertiesFromOptions(
      grafonnet.panel.table.standardOptions.withDecimals(2)
  ),
])
```

JSON:

```json
{
  "overrides": [
    {
      "matcher": {
        "id": "byName",
        "options": "some-name"
      }
      ...
    }
  ]
}
```
