### ISSUE TITLE
Add alert to TimeSeries Panel

### ISSUE THREAD

**Issue by RorFis** [grafana/grafonnet#88]
I can't find anything to add alerts to a TimeSeries panel. Is it possible ?

**Comment by malcolmholmes** [comment]
Alerts are no-longer tied to panels, they need to be created independently. We haven't addressed alerts in this library yet.

**Comment by RorFis** [comment]
Any idea on when this will be addressed ?

**Comment by Duologic** [comment]
Not yet.

Closing as duplicate of #69
