### ISSUE TITLE
Language server support

### ISSUE THREAD

**Issue by ebracho** [grafana/grafonnet#90]
The whole grafonnet library is generated by a function which means that language servers can't extract information about the object it returns. For a library of this size it would be great to have autocomplete in editors so that we don't have to tab over to a browser so often. One idea to accomplish this is to use the schema to generate a "documentation overlay" that wraps the generated api with matching function  signatures and doc comments. For example:

```jsonnet
// grafonnet/gen/grafonnet-vX.Y.Z/main.libsonnet

local grafonnet = import 'github.com/grafana/grafonnet/grafonnet-base/main.libsonnet';
local schemas = import './schemas.libsonnet';
local version = importstr './grafana-version';
local g = grafonnet.new(schemas, version);

{
  panel: {
    timeSeries: {
      // Creates a new timeSeries panel with a title.
      new(title): g.panel.timeSeries.new(title),
      // ..
    },
    // ...
  },
  // ...
}

**Comment by malcolmholmes** [comment]
Isn't this the same (effort) as making a static library?

**Comment by Duologic** [comment]
There are multiple ways to approach this problem.

Some of the proposals:
- generate static library
- generate static overlay (this issue)
- provide support for dynamic library in LSP (https://github.com/grafana/jsonnet-language-server/issues/110)

**Comment by ebracho** [comment]
I'd be more than happy to generate a static overlay on our end if that's not the direction this project wants to go in. I tried writing a script to do so but my Jsonnet functional programming skills just weren't up to par lol.

**Comment by Duologic** [comment]
@ebracho Grafonnet is now statically generated, which means it can work with the language server now.
