### ISSUE TITLE
Simplify fixed-color overrides

### ISSUE THREAD

**Issue by Noobnesz** [grafana/grafonnet#99]
Hi,

I have a code that looks like this to create a timeseries override.
```
...
+ standardOptions.withOverrides([
  fieldOverride.byName.new('latency_p99')
  + fieldOverride.byName.withPropertiesFromOptions(standardOptions.color.withFixedColor('green')),
...
])
```

I am using terraform to provision dashboards, and I got this rendered from the terraform plan:
```
...
properties = [
{
id    = "color.fixedColor"
value = "green"
},
...
```

The values for the `id` and the `value` keys do not look like valid override values and the override is not rendered at all, inspecting the json for the panel I am working on.

A properly working override looks like this:
```
"properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "green",
              "mode": "fixed"
            }
```

To correctly render the override, I have a workaround that looks like this, but it looks overly complicated just for overriding a color:
```
...
+ standardOptions.withOverrides([
  fieldOverride.byName.new('latency_p99')
  + fieldOverride.byName.withProperty('color', {
          fixedColor: 'green',
          mode: 'fixed',
        }),
...
])
```
I was wondering: is there a simpler way to do this? I expect a one liner such as `+ fieldOverride.byName.withPropertiesFromOptions(standardOptions.color.withFixedColor('green')),` would render the override properly.

**Comment by Duologic** [comment]
Thanks for reporting this, we're addressing this in #104
